<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <FahrenheitToCelsiusResponse xmlns="https://www.w3schools.com/xml/">
            <FahrenheitToCelsiusResult>23.8888888888889</FahrenheitToCelsiusResult>
        </FahrenheitToCelsiusResponse>
    </soap:Body>
</soap:Envelope>




        <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
    <getTestName xmlns="http://www.infodom.hr/egov">
        <id>VM\egop10service</id>
    </getTestName>
</soap:Body>
</soap:Envelope>


        <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
    <azurirajPismeno xmlns="http://www.infodom.hr/egov">
        <u_god>Uredska godina</u_god>
        <rbr_pred>Broj predmeta</rbr_pred>
        <jop>JOP</jop>
        <status>Status - 0 : 1</status>
        <napomena>Napomena</napomena>
    </azurirajPismeno>
</soap:Body>
</soap:Envelope>



        <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
    <azurirajKorisnika xmlns="http://www.infodom.hr/egov">
        <employee_no>Z39071</employee_no>
        <fname> Jovan </fname>
        <lname> Perišić </lname>
        <nadredjeni> Z39089 </nadredjeni>
        <rukovodioc> DA </rukovodioc>
        <u_jedinica> Kabinet ministra </u_jedinica>
        <radno_m> Naziv radnog mjesta </radno_m>
        <domen_ki> jovan.perisic </domen_ki>
        <domena> VM </domena>
        <jezik> BS </jezik>
        <status> 1 </status>
    </azurirajKorisnika>
</soap:Body>
</soap:Envelope>

<?xml version="1.0" encoding="UTF-8"?> <!--  -->
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost/apoteke-app/CORE/API/korisnici/index.php" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<SOAP-ENV:Body>
    <ns1:azurirajKorisnikaResponse>
        <return xsi:nil="true"/>
    </ns1:azurirajKorisnikaResponse>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>